### ISSUE TITLE
How are you using scss files for the theme?

### ISSUE THREAD

**Issue by AmmarCodes** [liamcain/obsidian-scripts-and-plugins#1]
May I ask how are you using the scss files in the theme?

Do you compile the files to `obsidian.css` when there's a change?

**Comment by liamcain** [comment]
Sorry, just seeing this now. Yes, after I make updates I just call `sass index.scss ~/Documents/Notes/obsidian.css` to compile it directly to my vault.

**Comment by AmmarCodes** [comment]
Nice trick, thanks!
